### ISSUE TITLE
Path Issues

### ISSUE THREAD

**Issue by dullj** [hudmol/as_spreadsheet_bulk_updater#1]
Hey @payten ,

We have our ASpace setup over paths:

- Staff -> https://dev-findingaids.archives.newschool.edu/staff/
- PUI -> https://dev-findingaids.archives.newschool.edu

I had to edit the routes.rb to get this to work on our setup. 

```
ArchivesSpace::Application.routes.draw do

  [AppConfig[:frontend_proxy_prefix], AppConfig[:frontend_prefix]].uniq.each do |prefix|

    scope prefix do
      match('/plugins/spreadsheet_bulk_updater/download' => 'spreadsheet_bulk_updater#download_form', :via => [:get])
      match('/plugins/spreadsheet_bulk_updater/download' => 'spreadsheet_bulk_updater#download', :via => [:post])
    end
  end
end
```

**Comment by payten** [comment]
Aha totally, missed the prefix handling.  I'll make sure this is included in the next version.  Thanks @dullj!
