### ISSUE TITLE
default to "publish=true" for added notes?

### ISSUE THREAD

**Issue by megan-mcshea** [hudmol/as_spreadsheet_bulk_updater#10]
We're trying to add notes to archival objects with the spreadsheet, and while the notes are added, they default to publish?=false, so they're not showing up in the PUI. Is this a possible bug? or are we doing it wrong?
(thank you for this great tool!)

**Comment by jambun** [comment]
Hi @megan-mcshea I think that is the intended behavior. I'll add this as a possible future enhancement.

**Comment by megan-mcshea** [comment]
Hello, thanks for the quick reply.
Just to clarify, the intended behavior is to add notes where the default is "publish=false"?

**Comment by megan-mcshea** [comment]
using workaround of publish all option at parent level post-update. thanks!
