### ISSUE TITLE
Installation instructions should specify to rename the unzipped plugin directory

### ISSUE THREAD

**Issue by trevorthornton** [hudmol/as_spreadsheet_bulk_updater#2]
After unzipping the plugin, the unzipped directory needs to be renamed from `as_spreadsheet_bulk_updater-1.0` to `as_spreadsheet_bulk_updater`. This isn't mentioned in the installation instructions but it won't work without it.

**Comment by payten** [comment]
Thanks @trevorthornton, have added an extra instruction.
