### ISSUE TITLE
Plugin can't load write_xlsx, ArchivesSpace won't start

### ISSUE THREAD

**Issue by trevorthornton** [hudmol/as_spreadsheet_bulk_updater#3]
System: ArchivesSpace 2.8.1, RHEL 7.8, Java JDK 1.8.0_262

1. Installed the plugin to `plugins/as_spreadsheet_bulk_updater`
2. Added 'as_spreadsheet_bulk_updater' to AppConfig[:plugins] 
3. Ran `./scripts/initialize-plugin.sh as_spreadsheet_bulk_updater`. Though it installed bundler, it doesn't look like it installed anything from the plugin's Gemfile:

```
[root@aspace-staging1 archivesspace]$ ./scripts/initialize-plugin.sh as_spreadsheet_bulk_updater

Successfully installed bundler-2.1.4
Parsing documentation for bundler-2.1.4
Done installing documentation for bundler after 6 seconds
1 gem installed
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.

The Gemfile specifies no dependencies
Bundle complete! 0 Gemfile dependencies, 1 gem now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
```
4. Starting up the application fails with this message in the log:

```
...
WARNING: ERROR: initialization failed
org.jruby.rack.RackInitializationException: no such file to load -- write_xlsx
        from org/jruby/RubyKernel.java:974:in `require'
        from /opt/archivesspace-v2.8.1/archivesspace/plugins/as_spreadsheet_bulk_updater/backend/model/spreadsheet_builder.rb:1:in `<main>'
...
```

**Comment by payten** [comment]
Thanks @trevorthornton,

It's possible your missing the `digitization_work_order` plugin dependency:

> https://github.com/hudmol/as_spreadsheet_bulk_updater#prerequisites

That plugin pulls in the `write_xlsx` gem and provides the UI for selecting the records to output to the spreadsheet.

**Comment by trevorthornton** [comment]
Correct. I missed the prerequisites. Sorry!
