### ISSUE TITLE
Additional Note Fields

### ISSUE THREAD

**Issue by ebrplSpecialCollections** [hudmol/as_spreadsheet_bulk_updater#5]
Has there been any talk of adding other note fields or giving the user the ability to add additional notes to the spreadsheet manually? My institution is interested in including the phsyloc field specifically.

**Comment by jambun** [comment]
Hi @ebrplSpecialCollections,

Yes that has been discussed, along with a few other enhancement ideas. I just added a list to the readme:
https://github.com/hudmol/as_spreadsheet_bulk_updater#enhancement-ideas

These could happen when someone has the free time and the inspiration, or when someone offers to fund the development.


Cheers,
James

**Comment by ebrplSpecialCollections** [comment]
Thanks, James!

Emily Ward, CA, MLIS (She/Her/Hers)
Digital Archivist- Librarian II
Special Collections
East Baton Rouge Parish Library
7711 Goodwood Blvd.
Baton Rouge, La. 70806
(225)231-3752

________________________________
