### ISSUE TITLE
db_error when generating spreadsheet

### ISSUE THREAD

**Issue by ebrplSpecialCollections** [hudmol/as_spreadsheet_bulk_updater#6]
Tried using this today and got this error.

{"error":{"db_error":["Database integrity constraint conflict: Java::ComMysqlJdbc::MysqlDataTruncation: Data truncation: Cannot create a JSON value from a string with CHARACTER SET 'binary'."]}}​

I tried exporting a spreadsheet from a couple of different resources and selected a couple of different fields to make sure there wasn't something going on with the original resource I was working with but got the same error.  I noticed some changes have been made since yesterday so, just wanted to give you a heads up.

**Comment by jambun** [comment]
Hi @ebrplSpecialCollections - are you on the latest version (v1.3.2)? Some recent versions were using `json_extract` which requires MySQL 5.7 or higher.
