### ISSUE TITLE
error when exporting bulk update spreadsheet

### ISSUE THREAD

**Issue by lparilla** [hudmol/as_spreadsheet_bulk_updater#8]
When I try to export the spreadsheet for a collection, I'm getting the following error. It is only appearing for one of the four series.   I've only copied the first part of the error report below. Thanks in advance!

{"error":"key not found: \"type\": org/jruby/RubyHash.java:1261:in `fetch'\n\t/archivesspace/plugins/as_spreadsheet_bulk_updater/backend/model/spreadsheet_builder.rb:340:in `block in calculate_subrecord_counts'\n\t/archivesspace/gems/gems/sequel-5.9.0/lib/sequel/dataset/actions.rb:151:in `block in each'\n\t/archivesspace/gems/gems/sequel-5.9.0/lib/sequel/adapters/jdbc.rb:795:in `process_result_set'\n\t/archivesspace/gems/gems/sequel-5.9.0/lib/sequel/adapters/jdbc.rb:726:in `block in fetch_rows'\n\t/archivesspace/gems/gems/sequel-...

**Comment by payten** [comment]
Hi @lparilla,

Is it possible one of the archival objects you are exporting has a note subrecord without a `type`? If so, it's a bug!  Please try the latest release:

https://github.com/hudmol/as_spreadsheet_bulk_updater/releases/tag/v1.5.1
